//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tools_Injector_Mod_Menu.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtLibName {
            get {
                return ((string)(this["txtLibName"]));
            }
            set {
                this["txtLibName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtToast {
            get {
                return ((string)(this["txtToast"]));
            }
            set {
                this["txtToast"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtName {
            get {
                return ((string)(this["txtName"]));
            }
            set {
                this["txtName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtSite {
            get {
                return ((string)(this["txtSite"]));
            }
            set {
                this["txtSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtText {
            get {
                return ((string)(this["txtText"]));
            }
            set {
                this["txtText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtEndCredit {
            get {
                return ((string)(this["txtEndCredit"]));
            }
            set {
                this["txtEndCredit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtImg {
            get {
                return ((string)(this["txtImg"]));
            }
            set {
                this["txtImg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtNDK {
            get {
                return ((string)(this["txtNDK"]));
            }
            set {
                this["txtNDK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int menuStyle {
            get {
                return ((int)(this["menuStyle"]));
            }
            set {
                this["menuStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkRemoveTemp {
            get {
                return ((bool)(this["chkRemoveTemp"]));
            }
            set {
                this["chkRemoveTemp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkTFiveCredit {
            get {
                return ((bool)(this["chkTFiveCredit"]));
            }
            set {
                this["chkTFiveCredit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkLogsComplie {
            get {
                return ((bool)(this["chkLogsComplie"]));
            }
            set {
                this["chkLogsComplie"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkLogsSuccess {
            get {
                return ((bool)(this["chkLogsSuccess"]));
            }
            set {
                this["chkLogsSuccess"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkLogsError {
            get {
                return ((bool)(this["chkLogsError"]));
            }
            set {
                this["chkLogsError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<service android:name=\"com.tfive.modmenu.FloatingModMenuService\" android:enabled=" +
            "\"true\" android:exported=\"false\" android:stopWithTask=\"true\"/>")]
        public string txtService {
            get {
                return ((string)(this["txtService"]));
            }
            set {
                this["txtService"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("invoke-static {p0}, Lcom/tfive/MainActivity;->Start(Landroid/content/Context;)V")]
        public string txtOnCreate {
            get {
                return ((string)(this["txtOnCreate"]));
            }
            set {
                this["txtOnCreate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<activity android:configChanges=""keyboardHidden|orientation|screenSize"" android:name=""com.tfivel.MainActivity"">
     <intent-filter>
         <action android:name=""android.intent.action.MAIN""/>
         <category android:name=""android.intent.category.LAUNCHER""/>
     </intent-filter>
</activity>")]
        public string txtActionMain {
            get {
                return ((string)(this["txtActionMain"]));
            }
            set {
                this["txtActionMain"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkSound {
            get {
                return ((bool)(this["chkSound"]));
            }
            set {
                this["chkSound"] = value;
            }
        }
    }
}
